spring:
  application:
    name: ai-code-helper
  profiles:
    active: dev
langchain4j:
  community:
    dashscope:
      chat-model:
        model-name: qwen-plus
        api-key: dashscope-api-key
      embedding-model:
        model-name: text-embedding-v4
        api-key: dashscope-api-key
bigmodel:
  api-key: bigmodel-api-key
